# Generated by Django 3.2.3 on 2021-05-27 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esko_app', '0014_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='user_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
