# Generated by Django 3.2.3 on 2021-05-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esko_app', '0018_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='commenter',
        ),
    ]
