# Generated by Django 3.2.3 on 2021-05-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esko_app', '0025_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
