# Generated by Django 3.2.3 on 2021-05-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esko_app', '0028_auto_20210530_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
