# Generated by Django 3.2.3 on 2021-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esko_app', '0030_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='tags', max_length=100),
            preserve_default=False,
        ),
    ]
